import { Student } from '../models/student.model';

export const MOCK_STUDENTS: Student[] = [
  {
    id: '1',
    photoUrl: 'assets/demo/images/avatar/amyelsner.png',
    admissionNumber: 'ADM-2024-001',
    rollNumber: '101',
    firstName: 'Arjun',
    lastName: 'Sharma',
    fullName: 'Arjun Sharma',
    class: '10',
    section: 'A',
    gender: 'Male',
    academicSession: '2024-2025',
    status: 'Active',
    contactNumber: '+91 9876543210',
    email: 'arjun.sharma@example.com',
    dateOfBirth: '2009-05-15',
    admissionDate: '2024-04-01',
    address: '123, Green Valley, New Delhi',
    parentName: 'Rajesh Sharma'
  },
  {
    id: '2',
    photoUrl: 'assets/demo/images/avatar/annafali.png',
    admissionNumber: 'ADM-2024-002',
    rollNumber: '102',
    firstName: 'Priya',
    lastName: 'Verma',
    fullName: 'Priya Verma',
    class: '10',
    section: 'A',
    gender: 'Female',
    academicSession: '2024-2025',
    status: 'Active',
    contactNumber: '+91 9876543211',
    email: 'priya.verma@example.com',
    dateOfBirth: '2009-08-22',
    admissionDate: '2024-04-01',
    address: '456, Blue Hills, New Delhi',
    parentName: 'Suresh Verma'
  },
  {
    id: '3',
    photoUrl: 'assets/demo/images/avatar/asiyajavayant.png',
    admissionNumber: 'ADM-2024-003',
    rollNumber: '103',
    firstName: 'Rohan',
    lastName: 'Gupta',
    fullName: 'Rohan Gupta',
    class: '10',
    section: 'B',
    gender: 'Male',
    academicSession: '2024-2025',
    status: 'Pending',
    contactNumber: '+91 9876543212',
    email: 'rohan.gupta@example.com',
    dateOfBirth: '2009-12-10',
    admissionDate: '2024-04-05',
    address: '789, Rose Garden, New Delhi',
    parentName: 'Amit Gupta'
  },
  {
    id: '4',
    photoUrl: 'assets/demo/images/avatar/bernardodominic.png',
    admissionNumber: 'ADM-2023-045',
    rollNumber: '201',
    firstName: 'Ananya',
    lastName: 'Singh',
    fullName: 'Ananya Singh',
    class: '11',
    section: 'C',
    gender: 'Female',
    academicSession: '2023-2024',
    status: 'Graduated',
    contactNumber: '+91 9876543213',
    email: 'ananya.singh@example.com',
    dateOfBirth: '2008-02-14',
    admissionDate: '2023-04-01',
    address: '321, Sunshine Apts, New Delhi',
    parentName: 'Vikram Singh'
  },
  {
    id: '5',
    photoUrl: 'assets/demo/images/avatar/elwinsharvill.png',
    admissionNumber: 'ADM-2024-005',
    rollNumber: '105',
    firstName: 'Kabir',
    lastName: 'Malhotra',
    fullName: 'Kabir Malhotra',
    class: '10',
    section: 'A',
    gender: 'Male',
    academicSession: '2024-2025',
    status: 'Inactive',
    contactNumber: '+91 9876543214',
    email: 'kabir.m@example.com',
    dateOfBirth: '2009-03-30',
    admissionDate: '2024-04-01',
    address: '555, Park Lane, New Delhi',
    parentName: 'Sunil Malhotra'
  }
];
